sudo: false
language: java
install: true
cache:
  directories:
  - $HOME/.m2
before_install:
- ./scripts/status-checks.sh verify
script:
- ./scripts/status-checks.sh test
- ./scripts/status-checks.sh coverage
after_success: 
env:
  global:
    secure: W8efq0DkBJFCzZvOIfSE2pNZxqjgLZ2LdlMy1oL1EJkP61ENGEZn5BCfSvuePHzckhYacVk4pvMh7CrNiNPL6jqbGx/XQsmhHviyMW/kpGvYGqiWUfXeSGtvClUjJBXMYbkfaeDg2ksVDa3L+4sZ45Z4YjUS8mBjhoG+Qy8zkZAc0yYZQJoIJFascgB2ykntb5/f09aHBhDer7K8uR+n0HenNhqstkddnPryQjkAekFroWSEHhS2kvSTWHZi1hl1sl7A1c/cioV0tVN14D961qxfXlQ6RuULhK9iGOm7y9oqSkEk8TRIKAn59x5nRc3BUl8PldlCsFZ7VqJ4enM0nlgkpY68q85bgYlUeX7eyecRreOmGmifj4lk2+MUfGiz2EjIxdIMoi5Hsh5YsfAZI3xf8eVA8chtT6o3naQ0MACgpHaS+L3zcK4CmFITR0fMCqUPH+ZuQm+UTE/pSFx9X0dVEdyXUTyVIbWYXff32qcYqIPDD+3YuIyWvWAE6yoLNiCO3pAT8TMjk5K1nZn8tKzBIZ4oQUwBnNswdB6Gt2iuvPHEkP22ZHT5oRwpRdmQiS6K3/iBCJ+ixzXhwI2B6EZbUfsTHpKvLS3kqlunsBd2MtTGvdRPBaOtzB+qdr60JHJ2UfzveZMu5QOLMFUDVszaKUzh6Tt99S3u0DzPMEs=
